<?php

/**
 * Generated by ZF2ModuleCreator
 */

namespace ModelMagic;

use Zend\ModuleManager\Feature\AutoloaderProviderInterface;
use Zend\ModuleManager\Feature\ConfigProviderInterface;

class Module implements AutoloaderProviderInterface, ConfigProviderInterface
{

    /**
     * Returns configuration to merge with application configuration
     *
     * @return array|\Traversable
     */
    public function getConfig()
    {
        return include __DIR__ . '/config/module.config.php';
    }

    /**
     * @return array|\Traversable
     */
    public function getServiceConfig()
    {
        return array(
            'factories' => array(
                'ModelMagic\EntityManager\EntityManager' => 'ModelMagic\Factory\EntityManagerFactory'
            ),
            'aliases' => array(
                'ModelMagic\EntityManager' => 'ModelMagic\EntityManager\EntityManager'
            )
        );
    }

    /**
     * Return an array for passing to Zend\Loader\AutoloaderFactory.
     *
     * @return array
     */
    public function getAutoloaderConfig()
    {
        return array(
            'Zend\Loader\StandardAutoloader' => array(
                'namespaces' => array(
                    // Autoload all classes from namespace 'ModelMagic' from '/module/ModelMagic/src/ModelMagic'
                    __NAMESPACE__ => __DIR__ . '/src/' . __NAMESPACE__,
                )
            )
        );
    }
}
